@Example.Identity.Api_HostAddress = http://localhost:5241

### Register
POST {{Example.Identity.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "example",
  "password": "password123"
}

### Login
# @name login
POST {{Example.Identity.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "example",
  "password": "password123"
}

### Get current user (protected)
GET {{Example.Identity.Api_HostAddress}}/api/auth/me
Authorization: Bearer {{login.response.body.token}}
